### PR TITLE
Count pixels placed output amount in place toast

### PR DESCRIPTION
**Pull request by Cyklon3000**
Simple counter that locally counts the amount of pixels placed successfully by the bot.
Amount is shown in the "Pixel platziert!"-toast (zs_success) with the format "...platziert! (#{n})"

### CODE REVIEW

**Comment by Bloeckchengrafik** [comment]
Wie wäre es mit einer Speicherung im LocalStorage?

**Comment by Cyklon3000** [comment]
"Fixed" Now no more global variable. 
Instead localStorage (pixelsPlacedThisSession) and null-query for initialisation.

**Comment by Cyklon3000** [comment]
Reopened (accidental close with force-push)

Resolved conflicts with main branch

**Comment by Cyklon3000** [comment]
Now using the `??` operator instead of an if query.
The syntax of the nullish coalescing operator (ES11) is as follows:
```js
const result = someValue ?? defaultValueIfNull;
```

Creddit @flloschy for pointing this out.

**Comment by flloschy** [comment]
:)

**Comment by Cyklon3000** [comment]
I guess I'll have to learn how to properly sync main branch updates, if this happens again without this finally being either accepted or refused as a macro feature...

**Pull request merged**
